server:
  port: 8761
eureka:
  instance:
    hostname: localhost # 主机名
  dashboard:
    enabled: true
    path: /
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
    register-with-eureka: false
    fetch-registry: false
    prefer-same-zone-eureka: true
  server:
    enable-self-preservation: true

